# Generated by Django 5.0.7 on 2024-07-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perslib',
            name='image_url',
        ),
    ]
