# Generated by Django 5.0.7 on 2024-07-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perslib', '0002_remove_perslib_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='perslib',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
